annotations:
  - border_color: '#00000000'
    border_style: ''
    color: '#808080FF'
    rotation: 0
    text_bold: false
    text_content: 10.0.0.1
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: -280.0
    y1: -80.0
    z_index: 0
  - border_color: '#00000000'
    border_style: ''
    color: '#808080FF'
    rotation: 0
    text_bold: false
    text_content: 10.0.0.2
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: -120.0
    y1: -200.0
    z_index: 1
  - border_color: '#00000000'
    border_style: ''
    color: '#808080FF'
    rotation: 0
    text_bold: false
    text_content: 10.0.0.5
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: 240.0
    y1: -80.0
    z_index: 2
  - border_color: '#00000000'
    border_style: ''
    color: '#808080FF'
    rotation: 0
    text_bold: false
    text_content: 10.0.0.6
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: 40.0
    y1: -200.0
    z_index: 3
  - border_color: '#00000000'
    border_style: ''
    color: '#808080FF'
    rotation: 0
    text_bold: false
    text_content: 192.168.1.1
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: -400.0
    y1: 0.0
    z_index: 4
  - border_color: '#00000000'
    border_style: ''
    color: '#808080FF'
    rotation: 0
    text_bold: false
    text_content: 192.168.2.1
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: 280.0
    y1: 0.0
    z_index: 5
  - border_color: '#00000000'
    border_style: ''
    color: '#808080FF'
    rotation: 0
    text_bold: false
    text_content: 192.168.1.10
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: -560.0
    y1: 120.0
    z_index: 6
  - border_color: '#00000000'
    border_style: ''
    color: '#808080FF'
    rotation: 0
    text_bold: false
    text_content: 192.168.2.10
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: 440.0
    y1: 120.0
    z_index: 7
  - border_color: '#808080FF'
    border_style: 4,2
    color: '#FFFFFFFF'
    line_end: null
    line_start: null
    thickness: 3
    type: line
    x1: -200.0
    y1: 0.0
    x2: 200.0
    y2: 0.0
    z_index: 8
  - border_color: '#00000000'
    border_style: ''
    color: '#808080FF'
    rotation: 0
    text_bold: false
    text_content: GRE Tunnel
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: -40.0
    y1: -40.0
    z_index: 9
  - border_color: '#00000000'
    border_style: ''
    color: '#808080FF'
    rotation: 0
    text_bold: false
    text_content: |-
      172.16.0.1
      255.255.255.252
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: -200.0
    y1: 40.0
    z_index: 10
  - border_color: '#00000000'
    border_style: ''
    color: '#808080FF'
    rotation: 0
    text_bold: false
    text_content: |-
      172.16.0.2
      255.255.255.252
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: 80.0
    y1: 40.0
    z_index: 11
smart_annotations: []
nodes:
  - boot_disk_size: null
    configuration:
      - name: ios_config.txt
        content: |-
          hostname ISP
          no ip domain-lookup
          !
          interface GigabitEthernet0/0
           description Link-to-SiteA
           ip address 10.0.0.2 255.255.255.252
           no shutdown
          !
          interface GigabitEthernet0/1
           description Link-to-SiteB
           ip address 10.0.0.6 255.255.255.252
           no shutdown
          !
          router bgp 65000
           bgp log-neighbor-changes
           neighbor 10.0.0.1 remote-as 65100
           neighbor 10.0.0.1 description SiteA
           neighbor 10.0.0.5 remote-as 65200
           neighbor 10.0.0.5 description SiteB
          !
          end
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n0
    image_definition: null
    label: ISP
    node_definition: iosv
    parameters: {}
    ram: null
    tags: []
    x: 0
    y: -200
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: GigabitEthernet0/0
        mac_address: null
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet0/1
        mac_address: null
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet0/2
        mac_address: null
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet0/3
        mac_address: null
        slot: 3
        type: physical
  - boot_disk_size: null
    configuration:
      - name: ios_config.txt
        content: |-
          hostname SiteA-R
          no ip domain-lookup
          !
          interface GigabitEthernet0/0
           description WAN-to-ISP
           ip address 10.0.0.1 255.255.255.252
           no shutdown
          !
          interface GigabitEthernet0/1
           description LAN-to-SiteA-SW
           ip address 192.168.1.1 255.255.255.0
           no shutdown
          !
          router bgp 65100
           bgp log-neighbor-changes
           neighbor 10.0.0.2 remote-as 65000
           network 10.0.0.0 mask 255.255.255.252   ! advertise WAN /30 only
          !
          end
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n1
    image_definition: null
    label: SiteA-R
    node_definition: iosv
    parameters: {}
    ram: null
    tags: []
    x: -240
    y: 0
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: GigabitEthernet0/0
        mac_address: null
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet0/1
        mac_address: null
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet0/2
        mac_address: null
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet0/3
        mac_address: null
        slot: 3
        type: physical
  - boot_disk_size: null
    configuration:
      - name: ios_config.txt
        content: |-
          hostname SiteB-R
          no ip domain-lookup
          !
          interface GigabitEthernet0/0
           description WAN-to-ISP
           ip address 10.0.0.5 255.255.255.252
           no shutdown
          !
          interface GigabitEthernet0/1
           description LAN-to-SiteB-SW
           ip address 192.168.2.1 255.255.255.0
           no shutdown
          !
          router bgp 65200
           bgp log-neighbor-changes
           neighbor 10.0.0.6 remote-as 65000
           network 10.0.0.4 mask 255.255.255.252
          !
          end
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n2
    image_definition: null
    label: SiteB-R
    node_definition: iosv
    parameters: {}
    ram: null
    tags: []
    x: 240
    y: 0
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: GigabitEthernet0/0
        mac_address: null
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet0/1
        mac_address: null
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet0/2
        mac_address: null
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet0/3
        mac_address: null
        slot: 3
        type: physical
  - boot_disk_size: null
    configuration:
      - name: node.cfg
        content: |-
          # Set the hostname
          hostname SiteA-PC

          # Create a user with specified credentials
          USERNAME=cisco
          PASSWORD=cisco

          # Configure eth0 with a static IP
          ifconfig eth0 192.168.1.10 netmask 255.255.255.0 up
          route add default gw 192.168.1.1 eth0

          # Configure eth1 to use DHCP
          dhclient eth1

          # Optional: Set DNS servers
          echo "nameserver 8.8.8.8" > /etc/resolv.conf
          echo "nameserver 8.8.4.4" >> /etc/resolv.conf
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n3
    image_definition: null
    label: "SiteA-PC\t"
    node_definition: desktop
    parameters: {}
    ram: null
    tags: []
    x: -440
    y: 160
    interfaces:
      - id: i0
        label: eth0
        mac_address: null
        slot: 0
        type: physical
  - boot_disk_size: null
    configuration:
      - name: node.cfg
        content: |-
          # Set the hostname
          hostname SiteB-PC

          # Create a user with specified credentials
          USERNAME=cisco
          PASSWORD=cisco

          # Configure eth0 with a static IP
          ifconfig eth0 192.168.2.10 netmask 255.255.255.0 up
          route add default gw 192.168.2.1 eth0

          # Configure eth1 to use DHCP
          dhclient eth1

          # Optional: Set DNS servers
          echo "nameserver 8.8.8.8" > /etc/resolv.conf
          echo "nameserver 8.8.4.4" >> /etc/resolv.conf
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n4
    image_definition: null
    label: SiteB-PC
    node_definition: desktop
    parameters: {}
    ram: null
    tags: []
    x: 440
    y: 160
    interfaces:
      - id: i0
        label: eth0
        mac_address: null
        slot: 0
        type: physical
links:
  - id: l0
    n1: n1
    n2: n0
    i1: i1
    i2: i1
    conditioning: {}
    label: iosv-1-GigabitEthernet0/0<->iosv-0-GigabitEthernet0/0
  - id: l1
    n1: n0
    n2: n2
    i1: i2
    i2: i1
    conditioning: {}
    label: iosv-0-GigabitEthernet0/1<->iosv-2-GigabitEthernet0/0
  - id: l2
    n1: n1
    n2: n3
    i1: i2
    i2: i0
    conditioning: {}
    label: "SiteA-R-GigabitEthernet0/1<->SiteA-PC\t-eth0"
  - id: l3
    n1: n2
    n2: n4
    i1: i2
    i2: i0
    conditioning: {}
    label: SiteB-R-GigabitEthernet0/1<->desktop-1-eth0
lab:
  description: ''
  notes: "CCNP ENCOR – Student Lab ✧ Configure & Verify a GRE Tunnel (IPv4)\n\nLab\
    \ objective:\nStarting from the provided “before” configs, build a GRE tunnel\
    \ between Site-A and Site-B routers and install static routes so the two LAN switches\
    \ can reach each other.\nWhen you finish, SiteA-SW (192.168.1.10) must ping SiteB-SW\
    \ (192.168.2.10) successfully through the tunnel.\n\n1 Lab topology\n\nNode\t\
    Role\tInterfaces / IPs (already in the startup-configs)\nSiteA-R (IOSv)\tCustomer-edge\
    \ router\tGi0/0 10.0.0.1/30 → ISP • Gi0/1 192.168.1.1/24\nSiteB-R (IOSv)\tCustomer-edge\
    \ router\tGi0/0 10.0.0.5/30 → ISP • Gi0/1 192.168.2.1/24\nISP (IOSv)\tTransit\
    \ provider\tGi0/0 10.0.0.2/30 ← A • Gi0/1 10.0.0.6/30 ← B\nSiteA-SW (IOSvL2)\t\
    Campus switch\tVLAN 1 192.168.1.10/24 → SiteA-R\nSiteB-SW (IOSvL2)\tCampus switch\t\
    VLAN 1 192.168.2.10/24 → SiteB-R\nBGP is already running between each site and\
    \ the ISP, advertising only the WAN /30s.\nDefault gateways on both switches already\
    \ point at their local routers.\n\n2 Before-you-begin checklist (5 min)\nBoot\
    \ the topology in CML and open consoles to all nodes.\n\nOn each router, confirm\
    \ that only the WAN networks exist in BGP:\n\nbash\nCopy\nEdit\nSiteA-R# show\
    \ ip bgp summary\nProve the starting reachability:\n\nSiteA-R# ping 10.0.0.5  ✅\
    \ success\n\nSiteA-SW# ping 192.168.2.10  ❌ fails (expected)\n\nEverything good?\
    \ --> proceed.\n\n3 Task 1 Create the GRE tunnel (both routers)\nTarget tunnel\
    \ network: 172.16.0.0/30\n  SiteA-R = 172.16.0.1/30  SiteB-R = 172.16.0.2/30\n\
    \n3.1 Configure on SiteA-R\nbash\nCopy\nEdit\nSiteA-R# configure terminal\nSiteA-R(config)#\
    \ interface Tunnel0\nSiteA-R(config-if)# ip address 172.16.0.1 255.255.255.252\n\
    SiteA-R(config-if)# tunnel source GigabitEthernet0/0\nSiteA-R(config-if)# tunnel\
    \ destination 10.0.0.5\nSiteA-R(config-if)# no shutdown\nSiteA-R(config-if)# end\n\
    3.2 Configure on SiteB-R\nbash\nCopy\nEdit\nSiteB-R# configure terminal\nSiteB-R(config)#\
    \ interface Tunnel0\nSiteB-R(config-if)# ip address 172.16.0.2 255.255.255.252\n\
    SiteB-R(config-if)# tunnel source GigabitEthernet0/0\nSiteB-R(config-if)# tunnel\
    \ destination 10.0.0.1\nSiteB-R(config-if)# no shutdown\nSiteB-R(config-if)# end\n\
    Why you typed that\n\ntunnel source = local WAN interface (public IP)\n\ntunnel\
    \ destination = remote WAN IP\n\nNo tunnel mode needed – GRE/IP is default on\
    \ IOSv.\n\n4 Task 2 Add static routes for the LANs (both routers)\n\nRouter\t\
    Command\nSiteA-R\tip route 192.168.2.0 255.255.255.0 172.16.0.2\nSiteB-R\tip route\
    \ 192.168.1.0 255.255.255.0 172.16.0.1\n(Configure in conf t mode, then end.)\n\
    \n5 Task 3 Verify your work (“green-lights”)\n\nStep\tCommand\tSuccess criteria\n\
    1\tshow ip interface brief\tTunnel0 on each router shows up / up\n2\tshow interfaces\
    \ tunnel0\tProtocol up, source/destination correct\n3\t`show ip route\tinc 192.168`\n\
    4\tping 172.16.0.2 (from SiteA-R)\t5 success replies\n5\tping 192.168.2.10 (from\
    \ SiteA-SW)\t5 success replies\n6\ttraceroute 192.168.2.10 (from SiteA-SW)\t1st\
    \ hop = 192.168.1.1, 2nd = 172.16.0.2\nIf any test fails:\n\nCheck spelling of\
    \ IP masks (/30 vs /24).\n\nEnsure you used the correct WAN IPs in tunnel destination.\n\
    \nConfirm the WAN /30s still ping across the ISP (BGP session up).\n\n6 Clean-up\
    \ & repetition cycle\nSave a snapshot named GRE-FINISHED.\n\nTo drill muscle memory,\
    \ revert to the initial snapshot (PRE-LAB), start the routers, and time yourself:\n\
    \n< 3 min = pass • < 2 min = goal • < 90 sec = automatic!\n\nRinse and repeat\
    \ until the configuration sequence is effortless.\n\n7 Quick-reference command\
    \ sheet\nbash\nCopy\nEdit\n! GRE interface (both ends)\ninterface Tunnel0\n ip\
    \ address <local-tun-IP> 255.255.255.252\n tunnel source GigabitEthernet0/0\n\
    \ tunnel destination <peer-WAN-IP>\n no shutdown\n\n! Static route for remote\
    \ LAN\nip route <remote-LAN> 255.255.255.0 <peer-tun-IP>\n\n! Verification\nshow\
    \ ip interface brief\nshow interfaces Tunnel0\nshow ip route static\nping <peer-tun-IP>\n\
    ping <remote-host>\nMemorize this block, practise until you can type it without\
    \ pausing, and the GRE-tunnel task on exam day will feel like second nature. Good\
    \ luck!"
  title: Configure & Verify a GRE Tunnel (IPv4)
  version: 0.3.0
